---
title: "Week 14 Slides"
subtitle: "Where to from here?"
author: "Andrew Katz"
institute: "Department of Engineering Education <br><br> Virginia Tech"
date: "2021-04-20"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r setup-chunk, echo = FALSE, message = FALSE}
library(tidyverse)
library(car)


xaringanExtra::use_panelset()


```


---

.center[

# Week 14 Announcements

]

--
### Great work on problem set 3

--

### Problem Set 4 due 4/22

--

### At-a-glance Key Terms Sheet due 05/04

--

### I have assigned week 1 (4/27) and week 2 (5/04) for projects

* Week 1 - Amy, Andrea, Alli, Rene, Sidd, Yasir

* Week 2 - Abe, Isil, Jeremy, Matt, Maya, Melissa, and Taylor




---

.center[
# Presentation Expectations
]

.pull-left[
### For presenter
* ~ 10 minutes of talking
* 1-2 minutes on your problem of interest
* 2-3 minutes on your data source(s)
* 2-3 minutes on your data analysis choices
* 2-3 minutes on your results
* 1-2 minutes on your conclusion
]


.pull-right[
### For audience
* Everyone is expected to ask questions of four presenters 
* You are assigned to the four people whose first names precede your first name
* Reminder: Abe, Alli, Amy, Andrea, Isil, Jeremy, Matt, Maya, Melissa, Rene, Sidd, Taylor, Yasir
  * Example: Yasir asks Melissa, Rene, Sidd, and Taylor
  * Example2: Alli asks Abe, Yasir, Taylor, and Sidd 
]

---

.center[
# Week 14 Reading Assignment

### None :)


]



---


# Today's Plan

--

### Causal Inference

--

### Factor Analysis and Structural Equation Modeling

--

### Hierarchical (aka Multilevel) Modeling

--

### Missing Data

--

### Bayesian Data Analysis


---
# Today's Goals

### Be familiar with the concepts discussed

--

### Be able to identify these concepts in practice

-- 

### Know where to go if you want to learn more

---

class: center, inverse, middle

# Causal Inference


---

# What do we know about causal inference?

(i.e., what does "Causation" even mean?)




---

# What is the problem?

* Fundamental Problem of Causal Inference


---

# As Aside About Probabilistic Graphical Models (PGMs)

* Notation
  * Directed acyclic graphs (DAGs)
  * Undirected graphs
  * Factor graphs (do not confuse with factor analysis)

---

# PGMs - 2

* Encoding relationships between variables (three kinds of structures)
* Observed variables noted differently than latent (or unobserved) variables

---

# Terminology

* Confounder

* Mediator

* Moderator


---

# Common Approaches to Causal Inference

* Randomized Control Trials

---

# Commons Approaches to Causal Inference - 2

* Difference-in-differences


---

# Common Approaches to Causal Inference - 3

* Instrumental Variables



---

# Common Approaches to Causal Inference - 4

* Regression Discontinuity


---

# Where to get started

* Video resources:
  * [useR! tutorial](https://www.youtube.com/watch?v=n8c-UK19hbA)
  * [Policy Evaluation course](https://www.youtube.com/playlist?list=PLS6tnpTr39sHcnk9KcoQVzDywxWRzVWHC)
  
* Text resources:
  * [Causal inference in R primer](http://dagitty.net/primer/)
  * [Causal Inference: What If](https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1268/2021/03/ciwhatif_hernanrobins_30mar21.pdf)

* R packages
  * [Daggity](https://cran.r-project.org/web/packages/dagitty/index.html)


---

class: inverse, middle, center

# Factor Analysis

---

# What is the problem?

* We want to measure latent traits (Factor Analysis)

* We want to measure relationships between latent traits (Structural Equation Modeling)

---

# Terminology of Factor Analysis

* Principal Component Analysis
* Exploratory Factor Analysis (EFA)
* Confirmatory Factor Analysis


---
# How does Factor Analysis work?

* Model the covariance of the observed variables
(See path diagram)

---

# Structural Equation Modeling (SEM) 

---

# Where to get started

* Video resources
  * [Stats of doom](https://www.youtube.com/watch?v=C5RJvMaHJNo)
  * [Lesa Hoffman course](https://www.youtube.com/playlist?list=PLqK8c2KO4db4vyeTG0BAibvmdMCPHf27u)

* Text resources:
  * [lavaan tutorial](https://lavaan.ugent.be/tutorial/index.html)

* R packages
  * [lavaan](https://cran.r-project.org/web/packages/lavaan/index.html)
    

---
class: inverse, middle, center

# Hierarchical Models

---

# What is the problem?

* The i.i.d. assumption

* Might want to make one model or several individual models

---

# How does HLM/MLM work?

* Account for nesting in the data


---

# Where might this come up?

* Students nested in classrooms

* Classrooms nested in universities

* Employees nested in companies


---

# Where to get started

* Video resources:
  * [Field video](https://www.youtube.com/watch?v=51SMnDN0ye0)
  * [Linear mixed effects models](https://www.youtube.com/watch?v=QCqF-2E86r0)

* Text resources:
  * [Tutorial](https://www.rensvandeschoot.com/tutorials/lme4/)

* R packages:
  * [lme4](https://cran.r-project.org/web/packages/lme4/index.html) 


---

class: inverse, middle, center

# Missing Data

---

# What is the problem?

* Data _might_ be systematically missing

---

# Kinds of missing data

* Missing Completely at Random (MCAR)

* Missing at Random (MAR)

* Missing Not at Random (MNAR or NMAR)

---

# MCAR

* Missingness is the same probability for all observations

---

# MAR

* Missingness probabilistically associated with the values of other predictors 


---

# NMAR

* Missingness associated with some unobserved predictors or on the missing value itself

---

# What to do

* Complete case analysis

* Data imputation
  * Mean imputation
  * Multiple imputation by chained equations


---

# Where to get started

* Video resources:
  * [Multiple imputation](https://www.youtube.com/watch?v=gQkd_MylHQ8)
  * [Missing data theory](https://www.youtube.com/watch?v=qlPs8Ioa56Y)

* Text resources:
  * [Flexible Imputation of Missing Data](https://stefvanbuuren.name/fimd/)
  * [Applied Missing Data Analysis](https://bookdown.org/mwheymans/bookmi/)

* R resources:
  * [mice](https://amices.org/mice/)
  * [amelia](https://cran.r-project.org/web/packages/Amelia/vignettes/amelia.pdf)


---
class: center, inverse, middle

# Bayesian Inference

---

# What is the problem?

* Point estimates

* Assumptions behind p values and hypothesis testing

---

# Bayes Theorem

$Pr(A|B)=\frac{\Pr(B|A)\Pr(A)}{\Pr(B|A)\Pr(A)+\Pr(B|\neg A)\Pr(\neg A)}$


---

# Big idea behind Bayesian Inference

#### Different interpretation of probability


$P(D\mid M) = \frac{P(D) * P(M\mid D)}{P(M)}$

$P(D) = \sum_MP(M,D)$


---

# Common terminology

* Likelihood
* Priors
* Posterior
* Probability of the evidence

---

# Where to get started

* Video resources:

  * [Paul Burkner useR! talk](https://www.youtube.com/watch?v=OUyB4kiJcWE)
  * [Richard McElreath Statistical Rethinking](https://www.youtube.com/playlist?list=PLDcUM9US4XdNM4Edgs7weiyIguLSToZRI)
  * [Ben Goodrich Bayesian Statistics for Social Science course](https://www.youtube.com/playlist?list=PLSZp9QshJ8wyPCgoQR0Kw3HDNuy1FEZH9)
  * [Aki Vehtari Bayesian Data Analysis course](https://www.youtube.com/playlist?list=PLBqnAso5Dy7O0IVoVn2b-WtetXQk5CDk6)
  * [Andrew Gelman on p values](https://www.youtube.com/watch?v=ZmbrsbYwRWw)

* Text resources:
  * [Bayesian Data Analysis](http://www.stat.columbia.edu/~gelman/book/BDA3.pdf)

* R packages:
  * [brms](https://cran.r-project.org/web/packages/brms/index.html)
  * [rstanarm](https://cran.r-project.org/web/packages/rstanarm/index.html)





---
Blank 1

---
Blank 2

---
Blank 3

---

  